// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqcbqrzlrqiwdhetlurb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxY2JxcnpscnFpd2RoZXRsdXJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0OTYzODUsImV4cCI6MjA2MTA3MjM4NX0.tymyWNnQdd4ONQz_3aGeMijNisVLwvY39wpNW0yBxaY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);